#!/usr/bin/env node
import { realpathSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type CssImportEntry = string | { path: string; layer: string };

type RunCliIo = {
  stdout?: (message: string) => void;
  stderr?: (message: string) => void;
};

const USAGE = `Usage:
  ink convert <input.css> <output.ts>

Example:
  pnpx jsr:@kraken/ink/cli convert src/styles.css src/lib/styles.ts`;

function toTemplateLiteral(value: string): string {
  return `\`${
    value
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${")
  }\``;
}

function toStringLiteral(value: string): string {
  return JSON.stringify(value);
}

function findCssRuleEnd(input: string, start: number): number {
  let quote: string | null = null;
  let parenDepth = 0;

  for (let index = start; index < input.length; index += 1) {
    const char = input[index];

    if (quote) {
      if (char === "\\") {
        index += 1;
        continue;
      }
      if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === "(") {
      parenDepth += 1;
      continue;
    }

    if (char === ")" && parenDepth > 0) {
      parenDepth -= 1;
      continue;
    }

    if (char === ";" && parenDepth === 0) {
      return index + 1;
    }
  }

  return input.length;
}

function parseCssImportRule(statement: string): CssImportEntry | null {
  const match = statement.match(
    /^@import\s+(?:(["'])(.*?)\1|url\(\s*(?:(["'])(.*?)\3|([^)]*?))\s*\))\s*([^;]*?)\s*;?$/is,
  );
  if (!match) {
    return null;
  }

  const path = (match[2] ?? match[4] ?? match[5] ?? "").trim();
  if (path.length === 0) {
    return null;
  }

  const suffix = (match[6] ?? "").trim();
  if (suffix.length === 0) {
    return path;
  }

  const layerMatch = suffix.match(/^layer\(\s*([^)]+?)\s*\)$/i);
  if (layerMatch) {
    const layer = layerMatch[1].trim();
    return layer.length > 0 ? { path, layer } : null;
  }

  return null;
}

function extractTopLevelImports(css: string): {
  imports: CssImportEntry[];
  css: string;
} {
  const imports: CssImportEntry[] = [];
  const ranges: Array<[number, number]> = [];
  let braceDepth = 0;
  let quote: string | null = null;

  for (let index = 0; index < css.length; index += 1) {
    const char = css[index];

    if (quote) {
      if (char === "\\") {
        index += 1;
        continue;
      }
      if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === "/" && css[index + 1] === "*") {
      index += 2;
      while (
        index < css.length &&
        !(css[index] === "*" && css[index + 1] === "/")
      ) {
        index += 1;
      }
      index += 1;
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === "{") {
      braceDepth += 1;
      continue;
    }

    if (char === "}" && braceDepth > 0) {
      braceDepth -= 1;
      continue;
    }

    if (
      braceDepth === 0 &&
      css.slice(index, index + "@import".length).toLowerCase() === "@import"
    ) {
      const end = findCssRuleEnd(css, index);
      const parsed = parseCssImportRule(css.slice(index, end));
      if (parsed) {
        imports.push(parsed);
        ranges.push([index, end]);
        index = end - 1;
      }
    }
  }

  if (ranges.length === 0) {
    return { imports, css };
  }

  let nextCss = "";
  let cursor = 0;
  for (const [start, end] of ranges) {
    nextCss += css.slice(cursor, start);
    cursor = end;
  }
  nextCss += css.slice(cursor);

  return { imports, css: nextCss };
}

function formatImportEntry(entry: CssImportEntry): string {
  if (typeof entry === "string") {
    return toStringLiteral(entry);
  }

  return `{ path: ${toStringLiteral(entry.path)}, layer: ${
    toStringLiteral(entry.layer)
  } }`;
}

function formatImportCall(imports: readonly CssImportEntry[]): string {
  if (imports.length === 1) {
    return `styles.import(${formatImportEntry(imports[0])});`;
  }

  const entries = imports.map((entry) => `  ${formatImportEntry(entry)},`)
    .join("\n");
  return `styles.import([\n${entries}\n]);`;
}

function formatTailwindCssAssignment(css: string): string {
  return `styles.tailwindCss = [\n  ${toTemplateLiteral(css)},\n];`;
}

/** Convert CSS source into an Ink TypeScript module. */
export function convertCssToTypeScript(css: string): string {
  const extracted = extractTopLevelImports(css);
  const stylesheetCss = extracted.css.trim();
  const parts = [
    "// Generated by @kraken/ink/cli convert.",
    'import ink from "@kraken/ink";',
    "",
    "const styles = new ink();",
  ];

  if (extracted.imports.length > 0) {
    parts.push("", formatImportCall(extracted.imports));
  }

  if (stylesheetCss.length > 0) {
    parts.push("", formatTailwindCssAssignment(stylesheetCss));
  }

  parts.push("", "export default styles;", "");
  return parts.join("\n");
}

/** Convert a CSS file into an Ink TypeScript module on disk. */
export async function convertCssFile(
  inputPath: string,
  outputPath: string,
): Promise<void> {
  const css = await readFile(inputPath, "utf8");
  const output = convertCssToTypeScript(css);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

function getRuntimeArgs(): string[] {
  const deno = (globalThis as { Deno?: { args?: string[] } }).Deno;
  if (Array.isArray(deno?.args)) {
    return [...deno.args];
  }

  const processValue = (globalThis as {
    process?: { argv?: string[] };
  }).process;
  return processValue?.argv?.slice(2) ?? [];
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Run the Ink CLI. Returns a process-style exit code. */
export async function runCli(
  args: readonly string[] = getRuntimeArgs(),
  io: RunCliIo = {},
): Promise<number> {
  const stdout = io.stdout ?? console.log;
  const stderr = io.stderr ?? console.error;
  const [command, inputPath, outputPath, ...rest] = args;

  if (command === "--help" || command === "-h") {
    stdout(USAGE);
    return 0;
  }

  if (
    command !== "convert" ||
    typeof inputPath !== "string" ||
    typeof outputPath !== "string" ||
    rest.length > 0
  ) {
    stderr(USAGE);
    return 1;
  }

  try {
    await convertCssFile(inputPath, outputPath);
    stdout(`Wrote ${outputPath}`);
    return 0;
  } catch (error) {
    stderr(`ink: ${getErrorMessage(error)}`);
    return 1;
  }
}

function isMainModule(): boolean {
  const importMeta = import.meta as ImportMeta & { main?: boolean };
  if (typeof importMeta.main === "boolean") {
    return importMeta.main;
  }

  const processValue = (globalThis as {
    process?: { argv?: string[] };
  }).process;
  const scriptPath = processValue?.argv?.[1];
  if (!scriptPath) {
    return false;
  }

  try {
    const modulePath = fileURLToPath(import.meta.url);
    return resolve(scriptPath) === modulePath ||
      realpathSync(scriptPath) === realpathSync(modulePath);
  } catch {
    return false;
  }
}

function exitProcess(code: number): void {
  const deno = (globalThis as { Deno?: { exit?: (code?: number) => never } })
    .Deno;
  if (typeof deno?.exit === "function") {
    deno.exit(code);
  }

  const processValue = (globalThis as {
    process?: { exit?: (code?: number) => never };
  }).process;
  if (typeof processValue?.exit === "function") {
    processValue.exit(code);
  }
}

if (isMainModule()) {
  runCli().then((code) => {
    if (code !== 0) {
      exitProcess(code);
    }
  });
}
