import {
  createClassName,
  CssSerializationOptions,
  FontSourceInput,
  fontsToConfig,
  ImportedThemesInput,
  isCssVarRef,
  isTailwindClassValue,
  mergeTailwindClassNames,
  prefixTailwindVariantClasses,
  RootVarInput,
  rootVarsToGlobalRules,
  StyleDeclaration,
  StyleSheet,
  StyleValue,
  TailwindClassValue,
  type ThemeMode,
  themesToConfig,
  toCssDeclaration,
  toCssGlobalRules,
  toCssLayerOrderRule,
  toCssRules,
  toTailwindVariantForNestedKey,
} from "./shared.js";

/** A style declaration or recursive array of declarations (merged left-to-right). */
type StyleDeclarationInput =
  | StyleDeclaration
  | TailwindClassValue
  | ResolvedStyleDefinition
  | readonly StyleDeclarationInput[];
/** Map of class keys to style declaration inputs. */
type StyleSheetInput = Record<string, StyleDeclarationInput>;
/** Normalized style entry split into CSS declarations and Tailwind class segments. */
type ResolvedStyleDefinition = {
  kind: "ink-style";
  declaration: StyleDeclaration;
  tailwindClassNames?: readonly string[];
};
/** Normalized stylesheet map keyed by style name. */
type NormalizedStyleSheet = Record<string, ResolvedStyleDefinition>;
/** Precompiled class name map keyed by style key. */
type CompiledMap<T extends StyleSheetInput> = Partial<Record<keyof T, string>>;
/** Variant group map: `{ groupName: { variantName: Partial<StyleSheet> } }`. */
type VariantSheet<T extends StyleSheetInput> = Record<
  string,
  Record<string, Partial<T>>
>;
/** Variant-specific global selector map applied from the active default selection. */
type VariantGlobalSheet = Record<string, Record<string, StyleSheetInput>>;
/** Precompiled variant class name map. */
type VariantClassMap<T extends StyleSheetInput> = Record<
  string,
  Record<string, Partial<Record<keyof T, string>>>
>;
/** Precompiled variant-scoped global CSS rules. */
type VariantGlobalRuleMap = Record<string, Record<string, string[]>>;
type BooleanVariantKey = "true" | "false";
type VariantSelectionValue<K> = K extends string
  ? string extends K ? string | boolean
  : K extends BooleanVariantKey ? boolean
  : K
  : K;
/** Selected variant values: `{ groupName: variantName }`. */
type VariantSelection<V extends VariantSheet<any> | undefined> = V extends
  VariantSheet<any> ? { [G in keyof V]?: VariantSelectionValue<keyof V[G]> }
  : Record<string, string | boolean>;
type SimpleVariantSheet = Record<string, Record<string, StyleDeclarationInput>>;
type SimpleVariantSelection<V extends SimpleVariantSheet | undefined> =
  V extends SimpleVariantSheet
    ? { [G in keyof V]?: VariantSelectionValue<keyof V[G]> }
    : Record<string, string | boolean>;

/** Configuration object accepted by `ink()`. */
type InkConfig<
  T extends StyleSheetInput,
  V extends VariantSheet<T> | undefined,
> = {
  /** Global stylesheet rules applied without class names. */
  global?: StyleSheetInput;
  /** Theme definitions expanded into root vars and scoped global rules. */
  themes?: ImportedThemesInput;
  /** Fontsource fonts expanded into package imports and `--font-*` variables. */
  fonts?: readonly FontSourceInput[];
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  root?: readonly RootVarInput[];
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  rootVars?: readonly RootVarInput[];
  /** Base stylesheet mapping class keys to declarations. */
  base?: T;
  /** Variant groups that conditionally override base styles. */
  variant?: V;
  /** Internal variant-scoped global selectors generated by the parser/Vite plugin. */
  variantGlobal?: VariantGlobalSheet;
  /** Default variant selections. */
  defaults?: VariantSelection<V>;
};
type InkSimpleConfig<V extends SimpleVariantSheet | undefined> = {
  /** Enable the single-slot shorthand mode. */
  simple: true;
  /** Global stylesheet rules applied without class names. */
  global?: StyleSheetInput;
  /** Theme definitions expanded into root vars and scoped global rules. */
  themes?: ImportedThemesInput;
  /** Fontsource fonts expanded into package imports and `--font-*` variables. */
  fonts?: readonly FontSourceInput[];
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  root?: readonly RootVarInput[];
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  rootVars?: readonly RootVarInput[];
  /** Direct style declaration used as the component's only slot. */
  base?: StyleDeclarationInput;
  /** Variant groups that conditionally override the shorthand base styles. */
  variant?: V;
  /** Default variant selections. */
  defaults?: SimpleVariantSelection<V>;
};
/** Build-time precompiled config passed as the second argument to `ink()`. */
type CompiledConfig<T extends StyleSheetInput> = {
  /** Whether stylesheet imports have been extracted. */
  imports?: true;
  /** Whether global rules have been extracted. */
  global?: true;
  /** Precompiled base class names. */
  base?: CompiledMap<T>;
  /** Precompiled variant class names. */
  variant?: VariantClassMap<T>;
  /** Precompiled variant-scoped global CSS rules. */
  variantGlobal?: VariantGlobalRuleMap;
};
/** Runtime options merged from `ink.config.ts` and passed as the third argument to `ink()`. */
type InkRuntimeOptions = CssSerializationOptions & {
  /** Utility declarations available for `@apply` references. */
  utilities?: StyleSheetInput;
  /** Theme expansion mode used for `themes`. */
  themeMode?: ThemeMode;
  /** Style resolution mode from `ink.config.ts`. */
  resolution?: "static" | "dynamic" | "hybrid";
  /** Dev-only debug logging settings injected by the Vite plugin. */
  debug?: {
    /** Internal gate so debug logs only run in the Vite dev server. */
    enabled?: boolean;
    /** Log dynamically injected style rules/class names. */
    logDynamic?: boolean;
    /** Log statically resolved class names/rules. */
    logStatic?: boolean;
  };
};
/** Input for {@link InkBuilder.addContainer} to register a container preset at runtime. */
type ContainerDefinitionInput = {
  /** Container name used in `@set` and `@<name>` shorthand. */
  name: string;
  /** CSS container type (defaults to `"inline-size"`). */
  type?: string;
  /** Container query condition (for example `"width < 20rem"`). */
  rule: string;
};
/** Maps each base style key to a {@link StyleAccessor} for class/style output. */
type Accessor<
  T extends StyleSheetInput,
  V extends VariantSheet<T> | undefined,
> = string extends keyof T ? Record<string, any>
  : {
    [K in keyof T]: StyleAccessor<V>;
  };
type InkSimpleStyleAccessor<V extends SimpleVariantSheet | undefined> =
  & ((variants?: SimpleVariantSelection<V>) => string)
  & {
    /** Return the CSS class name(s) for the shorthand style. */
    class: (variants?: SimpleVariantSelection<V>) => string;
    /** Return an inline style string for the shorthand style. */
    style: (variants?: SimpleVariantSelection<V>) => string;
  };
/** Callable accessor for a single style key that returns class names or inline styles. */
type StyleAccessor<V extends VariantSheet<any> | undefined> =
  & ((variants?: VariantSelection<V>) => string)
  & {
    /** Return the CSS class name(s) for this style key. */
    class: (variants?: VariantSelection<V>) => string;
    /** Return an inline style string for this style key. */
    style: (variants?: VariantSelection<V>) => string;
  };

const RUNTIME_STYLE_TAG_ID = "__ink_runtime_styles";
const RUNTIME_IMPORT_TAG_ID = "__ink_runtime_imports";
const RESOLVED_STYLE_KIND = "ink-style";
let runtimeManagedTagCounter = 0;
const injectedRules = new Set<string>();
const injectedImportRules = new Set<string>();
let lastInjectionDocument: DocumentLike | null = null;

type StyleTag = {
  id: string;
  appendChild(node: unknown): void;
  textContent?: string | null;
};

type DocumentLike = {
  getElementById(id: string): StyleTag | null;
  createElement(tag: "style"): StyleTag;
  createTextNode(text: string): unknown;
  head: { appendChild(node: unknown): void };
};

type InkBuilderOptions = {
  /** Enable the single-slot shorthand builder mode. */
  simple?: boolean;
};

const SIMPLE_STYLE_KEY = "__ink_simple__";

function hasVariantSelectionValue(
  value: unknown,
): value is string | number | symbol | boolean {
  return value !== undefined && value !== null;
}

function normalizeInkBuilderOptions(value: unknown): InkBuilderOptions {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  return { simple: (value as { simple?: unknown }).simple === true };
}

function wrapSimpleBaseInput(
  value: StyleDeclarationInput | undefined,
): StyleSheetInput | undefined {
  return value === undefined ? undefined : { [SIMPLE_STYLE_KEY]: value };
}

function wrapSimpleVariantInput(
  variants: SimpleVariantSheet | undefined,
): VariantSheet<Record<string, StyleDeclarationInput>> | undefined {
  if (!variants) {
    return undefined;
  }

  const wrapped: VariantSheet<Record<string, StyleDeclarationInput>> = {};
  for (const [group, groupVariants] of Object.entries(variants)) {
    const wrappedGroup: Record<
      string,
      Partial<Record<string, StyleDeclarationInput>>
    > = {};
    for (const [variantName, declaration] of Object.entries(groupVariants)) {
      wrappedGroup[variantName] = {
        [SIMPLE_STYLE_KEY]: declaration,
      };
    }
    wrapped[group] = wrappedGroup;
  }

  return wrapped;
}

function createEmptySimpleStyleAccessor<
  V extends SimpleVariantSheet | undefined,
>(): InkSimpleStyleAccessor<V> {
  const accessor = (() => "") as InkSimpleStyleAccessor<V>;
  accessor.class = () => "";
  accessor.style = () => "";
  return accessor;
}

function injectRule(rule: string): void {
  const doc = (globalThis as unknown as { document?: DocumentLike }).document;
  if (!doc) {
    return;
  }
  if (doc !== lastInjectionDocument) {
    injectedRules.clear();
    injectedImportRules.clear();
    lastInjectionDocument = doc;
  }
  if (injectedRules.has(rule)) {
    return;
  }

  let tag = doc.getElementById(RUNTIME_STYLE_TAG_ID);
  if (!tag) {
    tag = doc.createElement("style");
    tag.id = RUNTIME_STYLE_TAG_ID;
    doc.head.appendChild(tag);
  }

  tag.appendChild(doc.createTextNode(rule));
  injectedRules.add(rule);
}

function injectImportRule(rule: string): void {
  const doc = (globalThis as unknown as { document?: DocumentLike }).document;
  if (!doc) {
    return;
  }
  if (doc !== lastInjectionDocument) {
    injectedRules.clear();
    injectedImportRules.clear();
    lastInjectionDocument = doc;
  }
  if (injectedImportRules.has(rule)) {
    return;
  }

  let tag = doc.getElementById(RUNTIME_IMPORT_TAG_ID);
  if (!tag) {
    tag = doc.createElement("style");
    tag.id = RUNTIME_IMPORT_TAG_ID;
    doc.head.appendChild(tag);
  }

  tag.appendChild(doc.createTextNode(rule));
  injectedImportRules.add(rule);
}

function setManagedRules(tagId: string, rules: readonly string[]): void {
  const doc = (globalThis as unknown as { document?: DocumentLike }).document;
  if (!doc) {
    return;
  }

  let tag = doc.getElementById(tagId);
  if (!tag) {
    if (rules.length === 0) {
      return;
    }
    tag = doc.createElement("style");
    tag.id = tagId;
    doc.head.appendChild(tag);
  }

  tag.textContent = rules.join("");
}

function normalizeTailwindClassNames(
  classNames: readonly string[] | undefined,
): string[] | undefined {
  if (!classNames || classNames.length === 0) {
    return undefined;
  }

  const normalized = classNames
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);

  return normalized.length > 0 ? normalized : undefined;
}

function createResolvedStyleDefinition(
  declaration: StyleDeclaration = {},
  tailwindClassNames?: readonly string[],
): ResolvedStyleDefinition {
  const normalizedTailwind = normalizeTailwindClassNames(tailwindClassNames);
  return normalizedTailwind
    ? {
      kind: RESOLVED_STYLE_KIND,
      declaration,
      tailwindClassNames: normalizedTailwind,
    }
    : {
      kind: RESOLVED_STYLE_KIND,
      declaration,
    };
}

function isResolvedStyleDefinition(
  value: unknown,
): value is ResolvedStyleDefinition {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !isCssVarRef(value) &&
    "kind" in value &&
    (value as { kind?: unknown }).kind === RESOLVED_STYLE_KIND &&
    "declaration" in value &&
    isStyleDeclarationObject(
      (value as { declaration?: unknown }).declaration,
    ) &&
    (!("tailwindClassNames" in value) ||
      Array.isArray(
        (value as { tailwindClassNames?: unknown }).tailwindClassNames,
      ))
  );
}

function mergeResolvedStyleDefinitions(
  base: ResolvedStyleDefinition,
  next: ResolvedStyleDefinition,
): ResolvedStyleDefinition {
  return createResolvedStyleDefinition(
    mergeStyleDeclarations(base.declaration, next.declaration),
    [
      ...(base.tailwindClassNames ?? []),
      ...(next.tailwindClassNames ?? []),
    ],
  );
}

function hasStyleDeclarations(declaration: StyleDeclaration): boolean {
  for (const value of Object.values(declaration)) {
    if (isStyleLeafArray(value) || isPrimitiveStyleLeaf(value)) {
      return true;
    }
    if (isStyleDeclarationObject(value) && hasStyleDeclarations(value)) {
      return true;
    }
  }
  return false;
}

function prefixNestedTailwindClassNames(
  key: string,
  classNames: readonly string[] | undefined,
): string[] | undefined {
  if (!classNames || classNames.length === 0) {
    return undefined;
  }

  const variant = toTailwindVariantForNestedKey(key);
  if (!variant) {
    throw new Error(
      `tw() inside nested selector "${key}" is not supported. Use explicit Tailwind variant classes instead.`,
    );
  }

  return prefixTailwindVariantClasses(classNames, variant);
}

function isStyleDeclarationObject(value: unknown): value is StyleDeclaration {
  if (
    typeof value !== "object" ||
    value === null ||
    Array.isArray(value) ||
    isCssVarRef(value) ||
    isTailwindClassValue(value) ||
    isResolvedStyleDefinition(value)
  ) {
    return false;
  }

  for (const nested of Object.values(value)) {
    if (isStyleLeafArray(nested)) {
      continue;
    }
    if (
      typeof nested !== "string" &&
      typeof nested !== "number" &&
      !isCssVarRef(nested) &&
      !isStyleDeclarationObject(nested)
    ) {
      return false;
    }
  }

  return true;
}

function isPrimitiveStyleLeaf(value: unknown): boolean {
  return typeof value === "string" || typeof value === "number" ||
    isCssVarRef(value);
}

function isStyleLeafArray(value: unknown): value is readonly StyleValue[] {
  return Array.isArray(value) &&
    value.every((entry) => isPrimitiveStyleLeaf(entry));
}

function mergeStyleDeclarations(
  base: StyleDeclaration,
  next: StyleDeclaration,
): StyleDeclaration {
  const merged: Record<string, unknown> = { ...base };

  for (const [key, nextValue] of Object.entries(next)) {
    const previousValue = merged[key];
    if (
      isStyleDeclarationObject(previousValue) &&
      isStyleDeclarationObject(nextValue)
    ) {
      merged[key] = mergeStyleDeclarations(previousValue, nextValue);
      continue;
    }
    merged[key] = nextValue;
  }

  return merged as StyleDeclaration;
}

function normalizeStyleDeclarationInput(
  input: StyleDeclarationInput,
  options: {
    imports?: Set<string>;
    utilities?: NormalizedStyleSheet;
    containers?: Record<string, { type?: string; rule: string }>;
    allowTailwind?: boolean;
  } = {},
): ResolvedStyleDefinition {
  const allowTailwind = options.allowTailwind !== false;

  if (Array.isArray(input)) {
    let merged = createResolvedStyleDefinition();
    for (const entry of input) {
      merged = mergeResolvedStyleDefinitions(
        merged,
        normalizeStyleDeclarationInput(entry, options),
      );
    }
    return merged;
  }

  if (isResolvedStyleDefinition(input)) {
    if (!allowTailwind && (input.tailwindClassNames?.length ?? 0) > 0) {
      throw new Error(
        'tw() can only be used as a full style value or on a top-level "@apply" directive.',
      );
    }

    return createResolvedStyleDefinition(
      input.declaration,
      input.tailwindClassNames,
    );
  }

  if (isTailwindClassValue(input)) {
    if (!allowTailwind) {
      throw new Error(
        'tw() can only be used as a full style value or on a top-level "@apply" directive.',
      );
    }

    return createResolvedStyleDefinition({}, input.classNames);
  }

  const declaration = input as StyleDeclaration;
  let normalizedDeclaration: StyleDeclaration = {};
  let tailwindClassNames: string[] | undefined;

  for (const [key, value] of Object.entries(declaration)) {
    if (key === "@apply") {
      const applyValue = normalizeApplyInput(value, {
        ...options,
        allowTailwind,
      });
      normalizedDeclaration = mergeStyleDeclarations(
        normalizedDeclaration,
        applyValue.declaration,
      );
      tailwindClassNames = [
        ...(tailwindClassNames ?? []),
        ...(applyValue.tailwindClassNames ?? []),
      ];
      continue;
    }

    if (key === "@set") {
      const setValue = normalizeSetInput(value, options);
      normalizedDeclaration = mergeStyleDeclarations(
        normalizedDeclaration,
        setValue,
      );
      continue;
    }

    if (isStyleLeafArray(value) || isPrimitiveStyleLeaf(value)) {
      (normalizedDeclaration as Record<string, StyleValue>)[key] =
        value as StyleValue;
      continue;
    }

    if (
      Array.isArray(value) ||
      isStyleDeclarationObject(value) ||
      isResolvedStyleDefinition(value) ||
      isTailwindClassValue(value) ||
      (typeof value === "object" &&
        value !== null &&
        !isCssVarRef(value))
    ) {
      const nested = normalizeStyleDeclarationInput(
        value as StyleDeclarationInput,
        {
          ...options,
          allowTailwind,
        },
      );
      (normalizedDeclaration as Record<string, unknown>)[key] =
        nested.declaration;
      tailwindClassNames = [
        ...(tailwindClassNames ?? []),
        ...(prefixNestedTailwindClassNames(key, nested.tailwindClassNames) ??
          []),
      ];
      continue;
    }

    (normalizedDeclaration as Record<string, unknown>)[key] = value;
  }

  return createResolvedStyleDefinition(
    normalizedDeclaration,
    tailwindClassNames,
  );
}

function normalizeApplyInput(
  value: unknown,
  options: {
    imports?: Set<string>;
    utilities?: NormalizedStyleSheet;
    containers?: Record<string, { type?: string; rule: string }>;
    allowTailwind?: boolean;
  },
): ResolvedStyleDefinition {
  const allowTailwind = options.allowTailwind !== false;

  if (Array.isArray(value)) {
    let merged = createResolvedStyleDefinition();
    for (const entry of value) {
      merged = mergeResolvedStyleDefinitions(
        merged,
        normalizeApplyInput(entry, options),
      );
    }
    return merged;
  }

  if (isResolvedStyleDefinition(value)) {
    if (!allowTailwind && (value.tailwindClassNames?.length ?? 0) > 0) {
      throw new Error(
        'tw() can only be used as a full style value or on a top-level "@apply" directive.',
      );
    }

    return createResolvedStyleDefinition(
      value.declaration,
      value.tailwindClassNames,
    );
  }

  if (isTailwindClassValue(value)) {
    if (!allowTailwind) {
      throw new Error(
        'tw() can only be used as a full style value or on a top-level "@apply" directive.',
      );
    }

    return createResolvedStyleDefinition({}, value.classNames);
  }

  if (typeof value === "string") {
    const utility = options.utilities?.[value];
    if (!utility) {
      return createResolvedStyleDefinition();
    }
    return createResolvedStyleDefinition(
      utility.declaration,
      utility.tailwindClassNames,
    );
  }

  if (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !isCssVarRef(value) &&
    "rules" in value
  ) {
    const layeredApply = value as { rules: unknown; layer?: unknown };
    const rules = normalizeApplyInput(layeredApply.rules, options);
    const layeredDeclaration = hasStyleDeclarations(rules.declaration) &&
        typeof layeredApply.layer === "string" &&
        layeredApply.layer.trim().length > 0
      ? {
        [`@layer ${layeredApply.layer.trim()}`]: rules.declaration,
      }
      : rules.declaration;

    return createResolvedStyleDefinition(
      layeredDeclaration,
      rules.tailwindClassNames,
    );
  }

  if (
    isStyleDeclarationObject(value) ||
    Array.isArray(value) ||
    isResolvedStyleDefinition(value) ||
    isTailwindClassValue(value)
  ) {
    return normalizeStyleDeclarationInput(
      value as StyleDeclarationInput,
      options,
    );
  }

  return createResolvedStyleDefinition();
}

function normalizeSetInput(
  value: unknown,
  options: {
    containers?: Record<string, { type?: string; rule: string }>;
  },
): StyleDeclaration {
  if (Array.isArray(value)) {
    let merged: StyleDeclaration = {};
    for (const entry of value) {
      merged = mergeStyleDeclarations(
        merged,
        normalizeSetInput(entry, options),
      );
    }
    return merged;
  }

  if (typeof value === "string") {
    const preset = options.containers?.[value];
    return {
      containerName: value,
      containerType: preset?.type ?? "inline-size",
    };
  }

  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    const name = (value as { name?: unknown }).name;
    if (typeof name !== "string") {
      return {};
    }
    const type = (value as { type?: unknown }).type;
    return {
      containerName: name,
      containerType: typeof type === "string" ? type : "inline-size",
    };
  }

  return {};
}

function normalizeStyleSheetInput(
  styles: StyleSheetInput | undefined,
  options: {
    imports?: Set<string>;
    utilities?: NormalizedStyleSheet;
    containers?: Record<string, { type?: string; rule: string }>;
    allowTailwind?: boolean;
  } = {},
): NormalizedStyleSheet {
  const normalized: NormalizedStyleSheet = {};

  function addImportPaths(value: unknown): void {
    const entries = typeof value === "string" ||
        (typeof value === "object" && value !== null && !Array.isArray(value))
      ? [value]
      : Array.isArray(value)
      ? value
      : [];

    for (const entry of entries) {
      if (typeof entry === "string") {
        const trimmed = entry.trim();
        if (trimmed.length > 0) {
          options.imports?.add(`"${trimmed}"`);
        }
      } else if (
        typeof entry === "object" && entry !== null && "path" in entry
      ) {
        const pathEntry = entry as { path: string; layer?: string };
        if (typeof pathEntry.path === "string") {
          const trimmed = pathEntry.path.trim();
          if (trimmed.length > 0) {
            if (
              typeof pathEntry.layer === "string" &&
              pathEntry.layer.trim().length > 0
            ) {
              options.imports?.add(
                `"${trimmed}" layer(${pathEntry.layer.trim()})`,
              );
            } else {
              options.imports?.add(`"${trimmed}"`);
            }
          }
        }
      }
    }
  }

  if (!styles) {
    return normalized;
  }

  for (const [key, declaration] of Object.entries(styles)) {
    if (key === "@import") {
      addImportPaths(declaration);
      continue;
    }
    if (key === "@apply") {
      normalizeApplyInput(declaration, options);
      continue;
    }
    normalized[key] = normalizeStyleDeclarationInput(declaration, options);
  }

  return normalized;
}

function toDeclarationStyleSheet(styles: NormalizedStyleSheet): StyleSheet {
  const declarations: StyleSheet = {};
  for (const [key, style] of Object.entries(styles)) {
    declarations[key] = style.declaration;
  }
  return declarations;
}

function hasTailwindClassNames(style: ResolvedStyleDefinition): boolean {
  return (style.tailwindClassNames?.length ?? 0) > 0;
}

function resolveStyleClassValue(
  generatedClassName: string | undefined,
  style: ResolvedStyleDefinition,
): string {
  if (hasTailwindClassNames(style)) {
    return mergeTailwindClassNames([
      ...(generatedClassName ? [generatedClassName] : []),
      ...(style.tailwindClassNames ?? []),
    ]);
  }

  return generatedClassName ?? "";
}

function isInlineStyleValue(value: unknown): value is StyleValue {
  return typeof value === "string" || typeof value === "number" ||
    isCssVarRef(value) || isStyleLeafArray(value);
}

function mergeInlineDeclarations(
  ...declarations: readonly StyleDeclaration[]
): Record<string, StyleValue> {
  const merged: Record<string, StyleValue> = {};
  for (const declaration of declarations) {
    for (const [name, value] of Object.entries(declaration)) {
      if (!isInlineStyleValue(value)) {
        continue;
      }
      merged[name] = value;
    }
  }
  return merged;
}

function toInlineStyleString(
  declarations: readonly StyleDeclaration[],
  options?: CssSerializationOptions,
): string {
  const merged = mergeInlineDeclarations(...declarations);
  const parts: string[] = [];
  for (const [name, value] of Object.entries(merged)) {
    parts.push(toCssDeclaration(name, value, options));
  }
  return parts.join(";");
}

function normalizeVariantSheetInput<T extends StyleSheetInput>(
  variants: VariantSheet<T> | undefined,
  options: {
    imports?: Set<string>;
    utilities?: NormalizedStyleSheet;
    containers?: Record<string, { type?: string; rule: string }>;
    allowTailwind?: boolean;
  } = {},
): Record<string, Record<string, Partial<NormalizedStyleSheet>>> | undefined {
  if (!variants) {
    return undefined;
  }

  const normalized: Record<
    string,
    Record<string, Partial<NormalizedStyleSheet>>
  > = {};
  for (const [group, groupVariants] of Object.entries(variants)) {
    const normalizedGroup: Record<string, Partial<NormalizedStyleSheet>> = {};
    for (const [variantName, declarations] of Object.entries(groupVariants)) {
      const normalizedVariant: Partial<NormalizedStyleSheet> = {};
      for (const [key, declaration] of Object.entries(declarations)) {
        if (!declaration) {
          continue;
        }
        normalizedVariant[key] = normalizeStyleDeclarationInput(
          declaration as StyleDeclarationInput,
          {
            ...options,
            allowTailwind: true,
          },
        );
      }
      normalizedGroup[variantName] = normalizedVariant;
    }
    normalized[group] = normalizedGroup;
  }

  return normalized;
}

function normalizeVariantGlobalSheetInput(
  variants: VariantGlobalSheet | undefined,
  options: {
    imports?: Set<string>;
    utilities?: NormalizedStyleSheet;
    containers?: Record<string, { type?: string; rule: string }>;
    allowTailwind?: boolean;
  } = {},
): Record<string, Record<string, StyleSheet>> | undefined {
  if (!variants) {
    return undefined;
  }

  const normalized: Record<string, Record<string, StyleSheet>> = {};
  for (const [group, groupVariants] of Object.entries(variants)) {
    const normalizedGroup: Record<string, StyleSheet> = {};
    for (const [variantName, declarations] of Object.entries(groupVariants)) {
      const normalizedVariant = normalizeStyleSheetInput(declarations, {
        ...options,
        allowTailwind: false,
      });
      normalizedGroup[variantName] = toDeclarationStyleSheet(normalizedVariant);
    }
    normalized[group] = normalizedGroup;
  }

  return normalized;
}

function compileAccessorFactory<
  T extends StyleSheetInput,
  V extends VariantSheet<T> | undefined,
>(
  config: InkConfig<T, V>,
  compiled?: CompiledConfig<T>,
  runtimeOptions: InkRuntimeOptions = {},
  managedTagIds: { variantGlobal: string } = {
    variantGlobal: `__ink_runtime_variant_global_${runtimeManagedTagCounter +=
      1}`,
  },
): () => Accessor<T, V> {
  const resolution = runtimeOptions.resolution ?? "hybrid";
  const effectiveCompiled = resolution === "dynamic" ? undefined : compiled;
  const debugEnabled = runtimeOptions.debug?.enabled === true;
  const logDynamic = debugEnabled && runtimeOptions.debug?.logDynamic === true;
  const logStatic = debugEnabled && runtimeOptions.debug?.logStatic === true;
  const log = (mode: "dynamic" | "static", message: string): void => {
    if (
      (mode === "dynamic" && !logDynamic) || (mode === "static" && !logStatic)
    ) {
      return;
    }
    console.log(`[ink][${mode}] ${message}`);
  };

  const imports = new Set<string>();
  const utilities = runtimeOptions.utilities
    ? normalizeStyleSheetInput(runtimeOptions.utilities, {
      imports,
      containers: runtimeOptions.containers,
      allowTailwind: true,
    })
    : undefined;
  const normalizeOptions = {
    imports,
    utilities,
    containers: runtimeOptions.containers,
  };
  const cssOptions: CssSerializationOptions = {
    breakpoints: runtimeOptions.breakpoints,
    containers: runtimeOptions.containers,
    defaultUnit: runtimeOptions.defaultUnit,
  };

  const importedThemes = themesToConfig(
    config.themes,
    runtimeOptions.themeMode,
  );
  const importedFonts = fontsToConfig(config.fonts);
  for (const importPath of importedFonts.imports) {
    imports.add(importPath);
  }
  const rootVarStyles = rootVarsToGlobalRules([
    ...importedThemes.root,
    ...importedFonts.root,
    ...(config.root ?? config.rootVars ?? []),
  ]);
  const mergedGlobalStyles = {
    ...importedThemes.global,
    ...rootVarStyles,
    ...(config.global ?? {}),
  };
  const globalStyles = toDeclarationStyleSheet(
    normalizeStyleSheetInput(mergedGlobalStyles, {
      ...normalizeOptions,
      allowTailwind: false,
    }),
  );
  const styles = normalizeStyleSheetInput(config.base, {
    ...normalizeOptions,
    allowTailwind: true,
  });
  const variants = normalizeVariantSheetInput(
    config.variant as VariantSheet<T> | undefined,
    {
      ...normalizeOptions,
      allowTailwind: true,
    },
  );
  const variantGlobalStyles = normalizeVariantGlobalSheetInput(
    config.variantGlobal,
    {
      ...normalizeOptions,
      allowTailwind: false,
    },
  );
  const defaultSelection = (config.defaults ?? {}) as VariantSelection<V>;

  if (imports.size > 0 && !effectiveCompiled?.imports) {
    if (resolution === "static") {
      throw new Error(
        'ink resolution="static" requires @import rules to be statically extracted.',
      );
    }
    for (const importPath of imports) {
      injectImportRule(`@import ${importPath};`);
      log("dynamic", `@import ${importPath}`);
    }
  } else if (imports.size > 0) {
    for (const importPath of imports) {
      log("static", `@import ${importPath}`);
    }
  }

  const layerOrderRule = toCssLayerOrderRule(runtimeOptions.layers);
  if (layerOrderRule) {
    injectRule(layerOrderRule);
    log("dynamic", `layer order injected: ${layerOrderRule}`);
  }

  if (Object.keys(globalStyles).length > 0 && !effectiveCompiled?.global) {
    if (resolution === "static") {
      throw new Error(
        'ink resolution="static" requires global rules to be statically extracted.',
      );
    }
    for (const rule of toCssGlobalRules(globalStyles, cssOptions)) {
      injectRule(rule);
      log("dynamic", `global rule injected: ${rule}`);
    }
  } else if (Object.keys(globalStyles).length > 0) {
    for (const selector of Object.keys(globalStyles)) {
      log("static", `global selector: ${selector}`);
    }
  }

  const variantGlobalRules: string[] = [];
  const compiledVariantGlobal = effectiveCompiled?.variantGlobal;
  const resolvedDefaults = defaultSelection as Record<
    string,
    string | number | symbol | boolean | undefined
  >;
  for (const [group, variantName] of Object.entries(resolvedDefaults)) {
    if (!hasVariantSelectionValue(variantName)) {
      continue;
    }

    const normalizedVariantName = String(variantName);
    const compiledRules = compiledVariantGlobal?.[group]
      ?.[normalizedVariantName];
    if (compiledRules) {
      variantGlobalRules.push(...compiledRules);
      log("static", `variantGlobal.${group}.${normalizedVariantName}`);
      continue;
    }

    const declarations = variantGlobalStyles?.[group]?.[normalizedVariantName];
    if (!declarations) {
      continue;
    }

    if (resolution === "static") {
      throw new Error(
        `ink resolution="static" could not statically resolve variantGlobal.${group}.${normalizedVariantName}.`,
      );
    }

    const rules = toCssGlobalRules(declarations, cssOptions);
    variantGlobalRules.push(...rules);
    for (const rule of rules) {
      log(
        "dynamic",
        `variantGlobal.${group}.${normalizedVariantName} -> ${rule}`,
      );
    }
  }
  setManagedRules(managedTagIds.variantGlobal, variantGlobalRules);

  const accessors: Record<PropertyKey, unknown> = {};
  const variantClassMap: VariantClassMap<T> = {};
  const compiledBase = effectiveCompiled?.base;

  for (
    const [key, style] of Object.entries(styles) as [
      keyof T,
      ResolvedStyleDefinition,
    ][]
  ) {
    const compiledClassName = compiledBase?.[key];
    if (resolution === "static" && !compiledClassName) {
      throw new Error(
        `ink resolution="static" could not statically resolve base.${
          String(key)
        }.`,
      );
    }
    const generatedClassName = hasStyleDeclarations(style.declaration) ||
        !hasTailwindClassNames(style)
      ? createClassName(String(key), style.declaration, "runtime")
      : undefined;
    const classValue = compiledClassName ??
      resolveStyleClassValue(generatedClassName, style);

    if (!compiledClassName && generatedClassName) {
      for (
        const rule of toCssRules(
          generatedClassName,
          style.declaration,
          cssOptions,
        )
      ) {
        injectRule(rule);
      }
      log("dynamic", `base.${String(key)} -> ${classValue}`);
    } else {
      log("static", `base.${String(key)} -> ${classValue}`);
    }

    const resolveSelection = (selection?: VariantSelection<V>) =>
      selection
        ? ({ ...defaultSelection, ...selection } as VariantSelection<V>)
        : defaultSelection;

    const resolveVariantDeclarations = (
      selection?: VariantSelection<V>,
    ): StyleDeclaration[] => {
      if (!variants) {
        return [];
      }

      const resolvedSelection = resolveSelection(selection);
      const declarations: StyleDeclaration[] = [];

      for (
        const [group, variantName] of Object.entries(
          resolvedSelection as Record<
            string,
            string | number | symbol | boolean | undefined
          >,
        )
      ) {
        if (!hasVariantSelectionValue(variantName)) {
          continue;
        }

        const variantDeclaration = variants[group]?.[String(variantName)]
          ?.[String(key)];
        if (variantDeclaration) {
          declarations.push(variantDeclaration.declaration);
        }
      }

      return declarations;
    };

    const classAccessor = (selection?: VariantSelection<V>): string => {
      const resolvedSelection = selection
        ? ({ ...defaultSelection, ...selection } as VariantSelection<V>)
        : defaultSelection;
      const classNames = classValue ? [classValue] : [];
      let requiresTailwindMerge = false;

      for (
        const [group, variantName] of Object.entries(
          resolvedSelection as Record<
            string,
            string | number | symbol | boolean | undefined
          >,
        )
      ) {
        if (!hasVariantSelectionValue(variantName)) {
          continue;
        }

        const variantStyle = variants?.[group]?.[String(variantName)]
          ?.[String(key)];
        if (variantStyle && hasTailwindClassNames(variantStyle)) {
          requiresTailwindMerge = true;
        }

        const variantClass = variantClassMap[group]?.[String(variantName)]
          ?.[key];
        if (variantClass) {
          classNames.push(variantClass);
        }
      }

      if (classNames.length === 0) {
        return "";
      }

      if (classNames.length === 1) {
        return classNames[0];
      }

      return requiresTailwindMerge
        ? mergeTailwindClassNames(classNames)
        : classNames.join(" ");
    };

    const accessor = classAccessor as StyleAccessor<V>;
    accessor.class = classAccessor;
    accessor.style = (selection?: VariantSelection<V>) =>
      toInlineStyleString([
        style.declaration,
        ...resolveVariantDeclarations(selection),
      ], cssOptions);

    accessors[key] = accessor;
  }

  if (variants) {
    const compiledVariants = effectiveCompiled?.variant;

    for (const [group, groupVariants] of Object.entries(variants)) {
      const groupMap: Record<string, Partial<Record<keyof T, string>>> = {};
      const compiledGroup = compiledVariants?.[group];

      for (const [variantName, declarations] of Object.entries(groupVariants)) {
        const variantMap: Partial<Record<keyof T, string>> = {};
        const compiledVariant = compiledGroup?.[variantName];

        for (
          const [key, style] of Object.entries(declarations) as [
            keyof T,
            ResolvedStyleDefinition,
          ][]
        ) {
          const compiledClassName = compiledVariant?.[key];
          if (resolution === "static" && !compiledClassName) {
            throw new Error(
              `ink resolution="static" could not statically resolve variant.${group}.${variantName}.${
                String(key)
              }.`,
            );
          }
          const generatedClassName = hasStyleDeclarations(style.declaration) ||
              !hasTailwindClassNames(style)
            ? createClassName(
              `${group}:${variantName}:${String(key)}`,
              style.declaration,
              "runtime",
            )
            : undefined;
          const classValue = compiledClassName ??
            resolveStyleClassValue(generatedClassName, style);

          if (!compiledClassName && generatedClassName) {
            for (
              const rule of toCssRules(
                generatedClassName,
                style.declaration,
                cssOptions,
              )
            ) {
              injectRule(rule);
            }
            log(
              "dynamic",
              `variant.${group}.${variantName}.${String(key)} -> ${classValue}`,
            );
          } else {
            log(
              "static",
              `variant.${group}.${variantName}.${String(key)} -> ${classValue}`,
            );
          }

          variantMap[key] = classValue;
        }

        groupMap[variantName] = variantMap;
      }

      variantClassMap[group] = groupMap;
    }
  }

  const factory = () => accessors;
  return new Proxy(factory, {
    get(target, prop, receiver) {
      if (typeof prop === "string" && prop in accessors) {
        return (accessors as Record<string, unknown>)[prop];
      }
      return Reflect.get(target, prop, receiver);
    },
    has(target, prop) {
      if (typeof prop === "string" && prop in accessors) {
        return true;
      }
      return Reflect.has(target, prop);
    },
    ownKeys(target) {
      return Array.from(
        new Set([
          ...Reflect.ownKeys(target),
          ...Object.keys(accessors),
        ]),
      );
    },
    getOwnPropertyDescriptor(target, prop) {
      if (typeof prop === "string" && prop in accessors) {
        return {
          enumerable: true,
          configurable: true,
          writable: true,
        };
      }
      return Reflect.getOwnPropertyDescriptor(target, prop);
    },
  }) as unknown as () => Accessor<T, V>;
}

function compileSimpleConfig<V extends SimpleVariantSheet | undefined>(
  config: InkSimpleConfig<V>,
  compiled?: CompiledConfig<Record<string, StyleDeclarationInput>>,
  runtimeOptions: InkRuntimeOptions = {},
  managedTagIds: { variantGlobal: string } = {
    variantGlobal: `__ink_runtime_variant_global_${runtimeManagedTagCounter +=
      1}`,
  },
): InkSimpleStyleAccessor<V> {
  const wrappedConfig: InkConfig<
    Record<string, StyleDeclarationInput>,
    VariantSheet<Record<string, StyleDeclarationInput>> | undefined
  > = {
    global: config.global,
    themes: config.themes,
    fonts: config.fonts,
    root: config.root,
    rootVars: config.rootVars,
    base: wrapSimpleBaseInput(config.base),
    variant: wrapSimpleVariantInput(config.variant),
    defaults: config.defaults as VariantSelection<
      VariantSheet<Record<string, StyleDeclarationInput>> | undefined
    >,
  };
  const factory = compileAccessorFactory(
    wrappedConfig,
    compiled,
    runtimeOptions,
    managedTagIds,
  );
  const accessor = (factory() as Record<string, InkSimpleStyleAccessor<V>>)[
    SIMPLE_STYLE_KEY
  ] ?? createEmptySimpleStyleAccessor<V>();
  return accessor;
}

function compileConfig<
  T extends StyleSheetInput,
  V extends VariantSheet<T> | undefined,
>(
  config: InkConfig<T, V> | InkSimpleConfig<any>,
  compiled?: CompiledConfig<T>,
  runtimeOptions: InkRuntimeOptions = {},
  managedTagIds: { variantGlobal: string } = {
    variantGlobal: `__ink_runtime_variant_global_${runtimeManagedTagCounter +=
      1}`,
  },
): (() => Accessor<T, V>) | InkSimpleStyleAccessor<any> {
  if ((config as { simple?: boolean } | undefined)?.simple === true) {
    return compileSimpleConfig(
      config as InkSimpleConfig<any>,
      compiled as
        | CompiledConfig<Record<string, StyleDeclarationInput>>
        | undefined,
      runtimeOptions,
      managedTagIds,
    );
  }

  return compileAccessorFactory(
    config as InkConfig<T, V>,
    compiled,
    runtimeOptions,
    managedTagIds,
  );
}

const CONFIG_KEYS = new Set([
  "base",
  "global",
  "themes",
  "fonts",
  "root",
  "rootVars",
  "variant",
  "variantGlobal",
  "defaults",
]);

function normalizeConfigKey(key: string): string {
  return key === "rootVars" ? "root" : key;
}

/**
 * Builder returned by `new ink()` that supports incremental property assignment.
 *
 * Set config via `builder.base = ...`, `builder.variant = ...`, etc.
 * Access compiled styles via `builder()` (factory) or `builder.myKey()` (direct).
 * The builder compiles lazily on first access and recompiles when a config property changes.
 *
 * @template T The base stylesheet input type.
 * @template V The variant sheet type, or `undefined` if no variants are used.
 */
type InkBuilder<
  T extends StyleSheetInput = StyleSheetInput,
  V extends VariantSheet<T> | undefined = VariantSheet<T> | undefined,
> = {
  /** Call the builder as a factory to get the compiled style accessor. */
  (): Accessor<T, V>;
  /** Base stylesheet mapping class keys to style declarations. */
  base: T | undefined;
  /** Global stylesheet rules (selectors and at-rules applied without class names). */
  global: StyleSheetInput | undefined;
  /** Theme definitions expanded into root vars and scoped global rules. */
  themes: ImportedThemesInput | undefined;
  /** Fontsource fonts expanded into package imports and `--font-*` variables. */
  fonts: readonly FontSourceInput[] | undefined;
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  root: readonly RootVarInput[] | undefined;
  /** @deprecated Use `root` instead. */
  rootVars: readonly RootVarInput[] | undefined;
  /** Variant groups that conditionally override base styles. */
  variant: V | undefined;
  /** Default variant selections applied when no explicit selection is given. */
  defaults: VariantSelection<V> | undefined;
  /** Register a container preset for `@set` and `@<name>` shorthand at runtime. */
  addContainer(container: ContainerDefinitionInput): InkBuilder<T, V>;
  /** Add styles or external CSS files to the global stylesheet. */
  import(inputs: import("./shared.js").ImportInput): InkBuilder<T, V>;
} & Accessor<T, V>;

type InkSimpleBuilder<
  V extends SimpleVariantSheet | undefined = SimpleVariantSheet | undefined,
> = {
  /** Direct style declaration used as the component's only slot. */
  base: StyleDeclarationInput | undefined;
  /** Global stylesheet rules (selectors and at-rules applied without class names). */
  global: StyleSheetInput | undefined;
  /** Theme definitions expanded into root vars and scoped global rules. */
  themes: ImportedThemesInput | undefined;
  /** Fontsource fonts expanded into package imports and `--font-*` variables. */
  fonts: readonly FontSourceInput[] | undefined;
  /** CSS custom properties to emit on `:root` (optionally under a layer). */
  root: readonly RootVarInput[] | undefined;
  /** @deprecated Use `root` instead. */
  rootVars: readonly RootVarInput[] | undefined;
  /** Variant groups that conditionally override the shorthand base styles. */
  variant: V | undefined;
  /** Default variant selections applied when no explicit selection is given. */
  defaults: SimpleVariantSelection<V> | undefined;
  /** Register a container preset for `@set` and `@<name>` shorthand at runtime. */
  addContainer(container: ContainerDefinitionInput): InkSimpleBuilder<V>;
  /** Add styles or external CSS files to the global stylesheet. */
  import(inputs: import("./shared.js").ImportInput): InkSimpleBuilder<V>;
} & InkSimpleStyleAccessor<V>;

function createInkBuilder<
  T extends StyleSheetInput,
  V extends VariantSheet<T> | undefined,
>(
  compiled?: CompiledConfig<T>,
  runtimeOptions: InkRuntimeOptions = {},
): InkBuilder<T, V> {
  const config: Partial<InkConfig<T, V>> = {};
  const mutableContainers = { ...(runtimeOptions.containers ?? {}) };
  const managedTagIds = {
    variantGlobal: `__ink_runtime_variant_global_${runtimeManagedTagCounter +=
      1}`,
  };
  const effectiveRuntimeOptions: InkRuntimeOptions = {
    ...runtimeOptions,
    containers: mutableContainers,
  };
  let cachedFactory: (() => Accessor<T, V>) | null = null;

  function ensureCompiled(): () => Accessor<T, V> {
    if (!cachedFactory) {
      cachedFactory = compileAccessorFactory(
        config as InkConfig<T, V>,
        compiled,
        effectiveRuntimeOptions,
        managedTagIds,
      );
    }
    return cachedFactory;
  }

  const builder = function () {
    return ensureCompiled()();
  };
  const proxy = new Proxy(builder, {
    apply(_target, _thisArg, _args) {
      return ensureCompiled()();
    },
    set(_target, prop, value) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        (config as Record<string, unknown>)[normalizeConfigKey(prop)] = value;
        cachedFactory = null;
        return true;
      }
      return Reflect.set(_target, prop, value);
    },
    get(target, prop, receiver) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        return (config as Record<string, unknown>)[normalizeConfigKey(prop)];
      }
      if (typeof prop === "string" && !Reflect.has(target, prop)) {
        const accessor = ensureCompiled()();
        if (prop in accessor) {
          return (accessor as Record<string, unknown>)[prop];
        }
      }
      return Reflect.get(target, prop, receiver);
    },
    has(target, prop) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        return true;
      }
      if (typeof prop === "string" && !Reflect.has(target, prop)) {
        const accessor = ensureCompiled()();
        if (prop in accessor) {
          return true;
        }
      }
      return Reflect.has(target, prop);
    },
    ownKeys(target) {
      const accessor = ensureCompiled()();
      return Array.from(
        new Set([
          ...Reflect.ownKeys(target),
          ...CONFIG_KEYS,
          ...Object.keys(accessor),
        ]),
      );
    },
    getOwnPropertyDescriptor(target, prop) {
      if (
        typeof prop === "string" &&
        (CONFIG_KEYS.has(prop) || prop in ensureCompiled()())
      ) {
        return {
          enumerable: true,
          configurable: true,
          writable: true,
        };
      }
      return Reflect.getOwnPropertyDescriptor(target, prop);
    },
  }) as unknown as InkBuilder<T, V>;

  proxy.addContainer = (container: ContainerDefinitionInput) => {
    if (
      typeof container?.name !== "string" || container.name.length === 0 ||
      typeof container.rule !== "string"
    ) {
      throw new Error(
        "addContainer() expects { name: string, rule: string, type?: string }",
      );
    }

    mutableContainers[container.name] = {
      type: typeof container.type === "string" ? container.type : "inline-size",
      rule: container.rule,
    };
    cachedFactory = null;
    return proxy;
  };

  proxy.import = (inputs: import("./shared.js").ImportInput) => {
    const entries = Array.isArray(inputs) ? inputs : [inputs];
    config.global = config.global ?? {};
    const currentGlobal = config.global;

    for (const entry of entries) {
      if (
        typeof entry === "string" ||
        (typeof entry === "object" && entry !== null && "path" in entry)
      ) {
        currentGlobal["@import"] = currentGlobal["@import"] ?? [];
        if (Array.isArray(currentGlobal["@import"])) {
          (currentGlobal["@import"] as unknown as string[]).push(
            entry as string,
          );
        } else {
          currentGlobal["@import"] = [
            currentGlobal["@import"],
            entry as string,
          ] as unknown as import("./shared.js").StyleDeclaration;
        }
      } else if (typeof entry === "object" && entry !== null) {
        if ("rules" in entry) {
          const ruleObj = entry as import("./shared.js").ImportRuleObject;
          if (ruleObj.layer && typeof ruleObj.layer === "string") {
            currentGlobal[`@layer ${ruleObj.layer}`] = ruleObj.rules;
          } else {
            Object.assign(currentGlobal, ruleObj.rules);
          }
        } else {
          Object.assign(currentGlobal, entry);
        }
      }
    }

    cachedFactory = null;
    return proxy;
  };

  return proxy;
}

function createInkSimpleBuilder<
  V extends SimpleVariantSheet | undefined,
>(
  compiled?: CompiledConfig<Record<string, StyleDeclarationInput>>,
  runtimeOptions: InkRuntimeOptions = {},
): InkSimpleBuilder<V> {
  const config: Partial<InkSimpleConfig<V>> = {
    simple: true,
  };
  const mutableContainers = { ...(runtimeOptions.containers ?? {}) };
  const managedTagIds = {
    variantGlobal: `__ink_runtime_variant_global_${runtimeManagedTagCounter +=
      1}`,
  };
  const effectiveRuntimeOptions: InkRuntimeOptions = {
    ...runtimeOptions,
    containers: mutableContainers,
  };
  let cachedAccessor: InkSimpleStyleAccessor<V> | null = null;

  function ensureCompiled(): InkSimpleStyleAccessor<V> {
    if (!cachedAccessor) {
      cachedAccessor = compileSimpleConfig(
        config as InkSimpleConfig<V>,
        compiled,
        effectiveRuntimeOptions,
        managedTagIds,
      );
    }
    return cachedAccessor;
  }

  const builder = function (selection?: SimpleVariantSelection<V>) {
    return ensureCompiled()(selection);
  };
  const proxy = new Proxy(builder, {
    apply(_target, _thisArg, args) {
      return ensureCompiled()(args[0] as SimpleVariantSelection<V> | undefined);
    },
    set(_target, prop, value) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        (config as Record<string, unknown>)[normalizeConfigKey(prop)] = value;
        cachedAccessor = null;
        return true;
      }
      return Reflect.set(_target, prop, value);
    },
    get(target, prop, receiver) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        return (config as Record<string, unknown>)[normalizeConfigKey(prop)];
      }
      if (typeof prop === "string" && !Reflect.has(target, prop)) {
        const accessor = ensureCompiled();
        if (prop in accessor) {
          return (accessor as unknown as Record<string, unknown>)[prop];
        }
      }
      return Reflect.get(target, prop, receiver);
    },
    has(target, prop) {
      if (typeof prop === "string" && CONFIG_KEYS.has(prop)) {
        return true;
      }
      if (typeof prop === "string" && !Reflect.has(target, prop)) {
        const accessor = ensureCompiled();
        if (prop in accessor) {
          return true;
        }
      }
      return Reflect.has(target, prop);
    },
    ownKeys(target) {
      const accessor = ensureCompiled();
      return Array.from(
        new Set([
          ...Reflect.ownKeys(target),
          ...CONFIG_KEYS,
          ...Object.keys(accessor),
        ]),
      );
    },
    getOwnPropertyDescriptor(target, prop) {
      if (
        typeof prop === "string" &&
        (CONFIG_KEYS.has(prop) || prop in ensureCompiled())
      ) {
        return {
          enumerable: true,
          configurable: true,
          writable: true,
        };
      }
      return Reflect.getOwnPropertyDescriptor(target, prop);
    },
  }) as unknown as InkSimpleBuilder<V>;

  proxy.addContainer = (container: ContainerDefinitionInput) => {
    if (
      typeof container?.name !== "string" || container.name.length === 0 ||
      typeof container.rule !== "string"
    ) {
      throw new Error(
        "addContainer() expects { name: string, rule: string, type?: string }",
      );
    }

    mutableContainers[container.name] = {
      type: typeof container.type === "string" ? container.type : "inline-size",
      rule: container.rule,
    };
    cachedAccessor = null;
    return proxy;
  };

  proxy.import = (inputs: import("./shared.js").ImportInput) => {
    const entries = Array.isArray(inputs) ? inputs : [inputs];
    config.global = config.global ?? {};
    const currentGlobal = config.global;

    for (const entry of entries) {
      if (
        typeof entry === "string" ||
        (typeof entry === "object" && entry !== null && "path" in entry)
      ) {
        currentGlobal["@import"] = currentGlobal["@import"] ?? [];
        if (Array.isArray(currentGlobal["@import"])) {
          (currentGlobal["@import"] as unknown as string[]).push(
            entry as string,
          );
        } else {
          currentGlobal["@import"] = [
            currentGlobal["@import"],
            entry as string,
          ] as unknown as import("./shared.js").StyleDeclaration;
        }
      } else if (typeof entry === "object" && entry !== null) {
        if ("rules" in entry) {
          const ruleObj = entry as import("./shared.js").ImportRuleObject;
          if (ruleObj.layer && typeof ruleObj.layer === "string") {
            currentGlobal[`@layer ${ruleObj.layer}`] = ruleObj.rules;
          } else {
            Object.assign(currentGlobal, ruleObj.rules);
          }
        } else {
          Object.assign(currentGlobal, entry);
        }
      }
    }

    cachedAccessor = null;
    return proxy;
  };

  return proxy;
}

/**
 * Runtime stylesheet helper that generates class names and injects CSS rules.
 *
 * Call as `ink({ base, global, variant, defaults })` to compile styles immediately,
 * call as `ink({ simple: true, ... })` for the single-slot shorthand accessor,
 * or use `new ink()`/`new ink({ simple: true })` to create an incremental builder.
 */
export default function ink<
  T extends StyleSheetInput = StyleSheetInput,
  V extends VariantSheet<T> | undefined = VariantSheet<T> | undefined,
>(
  config?: InkConfig<T, V>,
  compiled?: CompiledConfig<T>,
  runtimeOptions?: InkRuntimeOptions,
): () => Accessor<T, V>;
export default function ink<
  V extends SimpleVariantSheet | undefined = SimpleVariantSheet | undefined,
>(
  config: InkSimpleConfig<V>,
  compiled?: CompiledConfig<Record<string, StyleDeclarationInput>>,
  runtimeOptions?: InkRuntimeOptions,
): InkSimpleStyleAccessor<V>;
export default function ink<
  T extends StyleSheetInput = StyleSheetInput,
  V extends VariantSheet<T> | undefined = VariantSheet<T> | undefined,
>(
  config?: InkConfig<T, V> | InkSimpleConfig<any> | InkBuilderOptions,
  compiled?: CompiledConfig<T>,
  runtimeOptions: InkRuntimeOptions = {},
):
  | (() => Accessor<T, V>)
  | InkSimpleStyleAccessor<any>
  | InkBuilder<T, V>
  | InkSimpleBuilder<any> {
  if (new.target) {
    const builderOptions = normalizeInkBuilderOptions(config);
    if (builderOptions.simple) {
      return createInkSimpleBuilder(
        compiled as
          | CompiledConfig<Record<string, StyleDeclarationInput>>
          | undefined,
        runtimeOptions,
      ) as InkSimpleBuilder<any>;
    }
    return createInkBuilder<T, V>(compiled, runtimeOptions);
  }
  return compileConfig(
    config as InkConfig<T, V> | InkSimpleConfig<any>,
    compiled,
    runtimeOptions,
  );
}

/** Re-exported builder type. */
export type {
  InkBuilder,
  InkBuilderOptions,
  InkSimpleBuilder,
  InkSimpleConfig,
  InkSimpleStyleAccessor,
};

/** Re-exported style types for convenience. */
export type { StyleDeclaration, StyleSheet, StyleValue } from "./shared.js";
